/* Components */
import ReviewForm from "@/src/components/ReviewForm";
import ThanksForm from "@/src/components/ThanksForm";
import UserForm from "@/src/components/UserForm";
import Head from "next/head";
import { GrFormPrevious, GrFormNext } from "react-icons/gr";
import { FiSend } from "react-icons/fi";

/* Hooks */
import useForm from "@/src/hooks/useForm";
import Steps from "@/src/components/Steps";

export default function Home() {
  const formComponents = [<UserForm />, <ReviewForm />, <ThanksForm />];
  const { currentStep, currentComponent, changeStep, isLastStep, isFirstStep } =
    useForm(formComponents);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/" />
      </Head>
      <main>
        <div className="app">
          <div className="header">
            <h2>Pesquisa UX</h2>
            <p>
              Com sua colaboração, vamos desenvolver o projeto Onebit-Social.
              Por favor, preencha o formulário abaixo e nos envie sua opinião.
            </p>
          </div>
          <div className="form-container">
            <Steps currentStep={currentStep} />
            <form onSubmit={(e) => changeStep(currentStep + 1, e)}>
              <div className="input-container">{currentComponent}</div>
              <div className="actions">
                {!isFirstStep && (
                  <button
                    type="button"
                    onClick={() => changeStep(currentStep - 1)}
                  >
                    <GrFormPrevious />
                    <span>Voltar</span>
                  </button>
                )}
                {!isLastStep ? (
                  <button>
                    <span>Avançar</span>
                    <GrFormNext
                      type="button"
                      onClick={() => changeStep(currentStep + 1)}
                    />
                  </button>
                ) : (
                  <button type="button">
                    <span>Enviar</span>
                    <FiSend />
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
