/* Styles */

/* Components */
import ReviewForm from "@/src/components/ReviewForm";
import ThanksForm from "@/src/components/ThanksForm";
import UserForm from "@/src/components/UserForm";
import Head from "next/head";
import { GrFormPrevious, GrFormNext } from "react-icons/gr";
import { FiSend } from "react-icons/fi";

/* Hooks */
import useForm from "@/src/hooks/useForm";
import Steps from "@/src/components/Steps";

export default function Home() {
  const formComponents = [<UserForm />, <ReviewForm />, <ThanksForm />];
  const { currentStep, currentComponent, changeStep, isLastStep, isFirstStep } =
    useForm(formComponents);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/" />
      </Head>
      <main>
        <div className="text-center pt-10 text-slate-100">
          <div>
            <h2 className="font-semibold text-2xl pb-2">Pesquisa UX</h2>
            <p>
              Com sua colaboração, vamos desenvolver o projeto Onebit-Social.
              Por favor, preencha o formulário abaixo e nos envie sua opinião.
            </p>
          </div>
          <div className="flex flex-col gap-5 h-screen items-center pt-20">
            <Steps currentStep={currentStep} />

            <form onSubmit={(e) => changeStep(currentStep + 1, e)}>
              <div>{currentComponent}</div>
              <div className="flex pt-10 gap-2">
                {!isFirstStep && (
                  <button
                    type="button"
                    onClick={() => changeStep(currentStep - 1)}
                    className="btn flex items-center gap-2"
                  >
                    <GrFormPrevious />
                    <span>Voltar</span>
                  </button>
                )}
                {!isLastStep ? (
                  <button
                    className="btn flex items-center gap-2"
                    type="button"
                    onClick={() => changeStep(currentStep + 1)}
                  >
                    <span>Avançar</span>
                    <GrFormNext />
                  </button>
                ) : (
                  <button type="button" className="btn flex items-center gap-2">
                    <span>Enviar</span>
                    <FiSend color="black" />
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
